# -*- coding: utf-8 -*-
"""Lab 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a1v45Xtsxp8BLEFEa8FgViMmgJ2ETzB6
"""

#Lab-01
#Problem-01

a=int(input("Enter 1st number: "))
b=int(input("Enter 2st number: "))
print("Product of the numbers: ",a*b)
if (a*b)>1000:
    print("Sum of the numbers: ",a+b)

#Problem-02

import math
r=float(input("Enter radius of the circle: "))

print("Area of the circle is: ",math.pi*(r**2))
print("Perimeter of the circle is: ",2*math.pi*r)

#Problem-03

def compound_interest_2019160106(P,R,T):
     return (P*(1+(R/100))**T)
P=int(input("Enter Principle Amount: "))
R=int(input("Enter Interest Rate: "))
T=int(input("Enter time in years: "))
print("Compound Interest, A= ",compound_interest_2019160106(P,R,T))

#Problem-04

N=int(input("Enter the nth value: "))
n=0
sum=0
for x in range(1,N+1):
    n= x**2
    sum= sum + n
print(sum)


#Problem-05

def prime_find_2019160106(N):
    
    for x in range(2,N):
        if N%x!=0:
           return N
        else:
            return 0
        
N=int(input("Enter the number: "))        
print(prime_find_2019160106(N),"is a prime number")

#Problem-06

def fibonacchi_2019160106(n):
 
    if n <= 1:
        return n
 
    return fibonacchi_2019160106(n - 1) + fibonacchi_2019160106(n - 2)
 
 
if __name__ == '__main__':
 
    n=int(input("Enter the nth number: "))
    print("Fibonacci number is", fibonacchi_2019160106(n))


#Problem-07

sum=0
num_list = [1, 3, 5,4,7,19,6,9,11,51]

for x in range(0,len(num_list)):
    sum= sum + num_list[x]

print("list",num_list)    
print("Sum= ",sum)

#Problem-08
sum=0
num_list = [1, 3, 5,4,7,19,6,9,11,51]

for x in range(0,len(num_list),2):
      sum= sum + num_list[x]
print("list",num_list)        
print("Sum of even index = ",sum)

#Problem-09
def largest_number_2019160106(num_list):
   return new_list[-1]

def smallest_number_2019160106(num_list):
    return new_list[0]

num_list = [34, 3, 5,4,7,19,6,9,11,51]
new_list = []

while num_list:
    min = num_list[0]  
    for x in num_list: 
        if x < min:
            min = x
    new_list.append(min)
    num_list.remove(min)    
     
print("Largest number in the list is :",largest_number_2019160106(num_list))
print("Smallest number in the list is :",smallest_number_2019160106(num_list))

#Problem-10
def second_largest_number_2019160106(num_list):
   return new_list[-2]

num_list = [34, 3, 5,4,7,19,6,9,11,51]
new_list = []

while num_list:
    min = num_list[0]  
    for x in num_list: 
        if x < min:
            min = x
    new_list.append(min)
    num_list.remove(min)    

print("2nd Largest number in the list is :",second_largest_number_2019160106(num_list))

#Problem-11

line = str(input("Enter a sentence or word: "))

print(line[0:-1:2])


#Problem-12

line = str(input("Enter a sentence or word: "))
n=int(input("Enter the value of n: "))

print(line[n+1:])

#Problem-13
line = str(input("Enter a sentence or word: "))
sub = str("CSE303")

l_str= len(line)
l_sub = len(sub)
c=0
for i in range(0,l_str-l_sub+1):
    if line[i:i+l_sub] == sub:
        c+=1
        
print("CSE303 apeared in the sentence for",c,"times")   

#Problem-14

def pallindrome_checker_2019160106(line):
      line= line.lower()
      if line == line[::-1]:
        return 1
       
line = str(input("Enter a word: "))

if pallindrome_checker_2019160106(line)==1:
          print(line,"is a pallindrome word")
else:
    print(line,"is not a pallindrome word")
    

#Problem-15
list1 = [34, 3, 5,4,7,19,6,9,11,51]
list2 = [5,12,45,68,34,57,43,7,9,12]    
new_list= []

for x in list1: 
    if x%2 != 0:
         new_list.append(x) 
         
for x in list2: 
    if x%2 == 0:
         new_list.append(x) 
         
print("First List:",list1)
print("Second List:",list2)
print("New list after getting odd number from first list and even number from second list:",new_list)